### ISSUE TITLE
unittest test cases not running

### ISSUE THREAD

**Issue by k1832** [sola-st/DynaPyt#42]
Maybe this is out-of-scope for DynaPyt, but `unittest` (the standard unit test framework) test cases do not run when the instrumentations are inserted.

## Before instrumentation

Source code:
```
import unittest

class TestSum(unittest.TestCase):
    def test_sum_2(self):
        self.assertEqual(2 + 5, 7)

if __name__ == "__main__":
    unittest.main()
```

Run result:
```
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

## After instrumentation

Source code (`_dynapyt_ast_` path is dummy):
```
# DYNAPYT: DO NOT INSTRUMENT


import dynapyt.runtime as _rt

_dynapyt_ast_ = "path/to/this-file/main.py" + ".orig"
try:
    import unittest
    
    class TestSum(_rt._attr_(_dynapyt_ast_, 0, unittest, "TestCase")):
        def test_sum_2(self):
            _rt._func_entry_(_dynapyt_ast_, 1, [lambda: self], "test_sum_2")
            _rt._call_(_dynapyt_ast_, 8, _rt._attr_(_dynapyt_ast_, 3, _rt._read_(_dynapyt_ast_, 2, lambda: self), "assertEqual"), False, [("", _rt._binary_op_(_dynapyt_ast_, 6, lambda: _rt._int_(_dynapyt_ast_, 4, 2), 0, lambda: _rt._int_(_dynapyt_ast_, 5, 5))), ("", _rt._int_(_dynapyt_ast_, 7, 7))], {})
            _rt._func_exit_(_dynapyt_ast_, 1, "test_sum_2")
    
    if _rt._enter_if_(_dynapyt_ast_, 12, _rt._comp_op_(_dynapyt_ast_, 9, __name__, [(0, "__main__")])):
        _rt._call_(_dynapyt_ast_, 11, _rt._attr_(_dynapyt_ast_, 10, unittest, "main"), False, [], {})
        _rt._exit_if_(_dynapyt_ast_, 12)
    else:
        _rt._exit_if_(_dynapyt_ast_, 12)
except Exception as _dynapyt_exception_:
    _rt._catch_(_dynapyt_exception_)
```

Run result
```

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by AryazE** [comment]
Thanks for raising this issue.
How are your running the instrumented code? Could the issue be with how `__name__` is resolved?

**Comment by k1832** [comment]
Oh sorry I didn't attach a command. Assuming the name of the source code below is `main.py`,
```
import unittest

class TestSum(unittest.TestCase):
    def test_sum_2(self):
        self.assertEqual(2 + 5, 7)

if __name__ == "__main__":
    unittest.main()
```
I just ran, `python3 main.py`

**Comment by AryazE** [comment]
I tested your approach and at least on Python 3.10 it crashes with `ModuleNotFoundError`, which is expected.
Running the instrumented code should be done with the `dynapyt.run_analysis` script and not directly with python. So the complete workflow should be:
```bash
python3 -m dynapyt.instrument.instrument --files main.py --analysis dynapyt.analyses.TraceAll.TraceAll
python3 -m dynapyt.run_analysis --entry main.py --analysis dynapyt.analyses.TraceAll.TraceAll
```
Let me know if this works.

**Comment by k1832** [comment]
Oh sorry my comment (https://github.com/sola-st/DynaPyt/issues/42#issuecomment-1757020406) was wrong.
I tested with the right run command (`python3 -m dynapyt.run_analysis --entry main.py --analysis dynapyt.analyses.TraceAll.TraceAll`) but the test case was still not triggered.

```
> python -m dynapyt.run_analysis --entry main.py --analysis dynapyt.analyses.TraceAll.TraceAll

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by AryazE** [comment]
Could you please also share your Python version and DynaPyt version so I can replicate the issue?

**Comment by k1832** [comment]
Sorry again for the late reply again.

I just retried with the clean version of the DynaPyt and still seeing the behavior.
Python ver.: 3.11.0
DynaPyt ver.: v1.4.0

To add to this, here is how I installed DynaPyt, and ran analysis.
```
git clone https://github.com/sola-st/DynaPyt.git
cd DynaPyt
pip install .

# Assume that I have `main.py` in the working directory
python3 -m dynapyt.instrument.instrument --files main.py --analysis dynapyt.analyses.TraceAll.TraceAll
python3 -m dynapyt.run_analysis --entry main.py --analysis dynapyt.analyses.TraceAll.TraceAll
```

**Comment by AryazE** [comment]
Thanks for the update. I can reproduce the problem too.
It seems that the test discovery of `unittest` is not compatible with how we instrument the code and run the analysis.
I have not tried this myself, but one thing to try is to pass your code as a module for the `--entry` argument (you have to convert it to a package and use the dotted path).
I will try to investigate it further, but it will probably take some time.

**Comment by AryazE** [comment]
I have some good news for you @k1832 
With the [new way](https://github.com/sola-st/DynaPyt?tab=readme-ov-file#new) of running DynaPyt, this case is resolved.
Please check it out and let me know if it works.

**Comment by k1832** [comment]
Oh thanks for letting me know! Since I don't have a plan to run this way for a while (and I believe this is no longer an issue), let me close this for now. 

Thanks again!
